### ISSUE TITLE
scrapy-redis conflict with scrapyd

### ISSUE THREAD

**Issue by linkkong** [rmax/scrapy-redis#109] opened 2017-08-22 10:18 UTC
When I deploy my project with scrapy-redis to scrapyd , it call me the errors:
class XXXXDetailSpider(RedisSpider):

2017-08-22 18:04:31 [twisted] CRITICAL: Unhandled error in Deferred:
2017-08-22 18:04:31 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 76, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 99, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/scrapy_redis/spiders.py", line 153, in from_crawler
    obj = super(RedisSpider, self).from_crawler(crawler, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/spiders/__init__.py", line 51, in from_crawler
    spider = cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_job'

And my env is   ubuntu16.04 + scrapy1.4 +scrapy-redis+scrapyd.   
When I don't use        class XXXXDetailSpider(RedisSpider):   but (Spider),it has no this error
maybe it is a new problem.

**Comment by amigcamel** [comment] 2019-03-28 09:15
Check this out: https://stackoverflow.com/q/35585956/1105489
I guess it has nothing to do with Scrapyd or scrapy-redis, but just that you redefined `__init__ in your subclass.

**Comment by Digenis** [comment] 2019-04-26 11:22
See the documentation https://scrapyd.readthedocs.io/en/stable/api.html#schedule-json
> Spiders scheduled with scrapyd should allow for an arbitrary number of keyword arguments...

Not a bug and not relevant to scrapy-redis at all.
You should close this issue.

**Closed** 2022-01-04 15:51 UTC
